name: Network Brouhaha
title: Network Brouhaha
description: Networking, Cloud, Automation, Infrastructure, Containers and General Geekery
url: https://networkbrouhaha.com
markdown: kramdown
theme: jekyll-theme-modernist
permalink: /:year/:month/:title/
show_downloads: false
exclude: ["README.md"]
plugins:
#  - jekyll-crosspost-to-medium
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "page:num"

author:
  name: Matt Elliott
  github: shamsway
  twitter: networkbrouhaha
  linkedin: eth0
  bio: Matt Elliott is a Network Architect/Engineer. CCIE #56011

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: "networkbrouhaha"

#jekyll-crosspost_to_medium:
#  enabled: true
#  cache: .jekyll-crosspost_to_medium
#  status: public
#  license: all-rights-reserved
#  backdate: true

rss_path: feed/
categories_path: categories/
tags_path: tags/
