name: Network Brouhaha
title: Network Brouhaha
description: Networking, Cloud, Automation, Infrastructure, Containers and General Geekery
markdown: kramdown
theme: jekyll-theme-modernist
permalink: /:year/:month/:title/
show_downloads: false
exclude: ["README.md"]

paginate: 10
paginate_path: "page:num"

author:
  name: Matt Elliott
  github: shamsway
  twitter: networkbrouhaha
  linkedin: eth0
  bio: Matt Elliott is a Network Architect/Engineer. CCIE #56011

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: "networkbrouhaha"

rss_path: feed/
categories_path: categories/
tags_path: tags/
